// Code generated by the Pulumi Terraform Bridge (tfgen) Tool DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package config

import (
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi/config"
)

// This is the Redis Cloud API key. It must be provided but can also be set by the `REDISCLOUD_ACCESS_KEY` environment
// variable.
func GetApiKey(ctx *pulumi.Context) string {
	v, err := config.Try(ctx, "rediscloud:apiKey")
	if err == nil {
		return v
	}
	return getEnvOrDefault("", nil, "REDISCLOUD_API_KEY").(string)
}

// This is the Redis Cloud API secret key. It must be provided but can also be set by the `REDISCLOUD_SECRET_KEY`
// environment variable.
func GetSecretKey(ctx *pulumi.Context) string {
	v, err := config.Try(ctx, "rediscloud:secretKey")
	if err == nil {
		return v
	}
	return getEnvOrDefault("", nil, "REDISCLOUD_SECRET_KEY").(string)
}

// This is the URL of Redis Cloud and will default to `https://api.redislabs.com/v1`. This can also be set by the
// `REDISCLOUD_URL` environment variable.
func GetUrl(ctx *pulumi.Context) string {
	return config.Get(ctx, "rediscloud:url")
}
