// Code generated by the Pulumi Terraform Bridge (tfgen) Tool DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package rediscloud

import (
	"context"
	"reflect"

	"errors"
	"github.com/RedisLabs/pulumi-rediscloud/sdk/go/rediscloud/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumix"
)

// Creates a Role in your Redis Enterprise Cloud Account.
//
// ## Example Usage
//
// ```go
// package main
//
// import (
//
//	"github.com/RedisLabs/pulumi-rediscloud/sdk/go/rediscloud"
//	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
//
// )
//
//	func main() {
//		pulumi.Run(func(ctx *pulumi.Context) error {
//			_, err := rediscloud.NewAclRule(ctx, "rule-resource", &rediscloud.AclRuleArgs{
//				Rule: pulumi.String("+@read ~cache:*"),
//			})
//			if err != nil {
//				return err
//			}
//			_, err = rediscloud.NewAclRole(ctx, "role-resource", &rediscloud.AclRoleArgs{
//				Rules: rediscloud.AclRoleRuleArray{
//					&rediscloud.AclRoleRuleArgs{
//						Name: rule_resource.Name,
//						Databases: rediscloud.AclRoleRuleDatabaseArray{
//							&rediscloud.AclRoleRuleDatabaseArgs{
//								Subscription: pulumi.Any(rediscloud_subscription.SubscriptionResource.Id),
//								Database:     pulumi.Any(rediscloud_subscription_database.DatabaseResource.Db_id),
//							},
//						},
//					},
//				},
//			})
//			if err != nil {
//				return err
//			}
//			return nil
//		})
//	}
//
// ```
//
// ## Import
//
// `rediscloud_acl_role` can be imported using the Identifier of the Role, e.g.
//
// ```sh
//
//	$ pulumi import rediscloud:index/aclRole:AclRole role-resource 123456
//
// ```
type AclRole struct {
	pulumi.CustomResourceState

	// A meaningful name for the role. Must be unique.
	Name pulumi.StringOutput `pulumi:"name"`
	// A set of rule association objects, documented below.
	Rules AclRoleRuleArrayOutput `pulumi:"rules"`
}

// NewAclRole registers a new resource with the given unique name, arguments, and options.
func NewAclRole(ctx *pulumi.Context,
	name string, args *AclRoleArgs, opts ...pulumi.ResourceOption) (*AclRole, error) {
	if args == nil {
		return nil, errors.New("missing one or more required arguments")
	}

	if args.Rules == nil {
		return nil, errors.New("invalid value for required argument 'Rules'")
	}
	opts = internal.PkgResourceDefaultOpts(opts)
	var resource AclRole
	err := ctx.RegisterResource("rediscloud:index/aclRole:AclRole", name, args, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// GetAclRole gets an existing AclRole resource's state with the given name, ID, and optional
// state properties that are used to uniquely qualify the lookup (nil if not required).
func GetAclRole(ctx *pulumi.Context,
	name string, id pulumi.IDInput, state *AclRoleState, opts ...pulumi.ResourceOption) (*AclRole, error) {
	var resource AclRole
	err := ctx.ReadResource("rediscloud:index/aclRole:AclRole", name, id, state, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// Input properties used for looking up and filtering AclRole resources.
type aclRoleState struct {
	// A meaningful name for the role. Must be unique.
	Name *string `pulumi:"name"`
	// A set of rule association objects, documented below.
	Rules []AclRoleRule `pulumi:"rules"`
}

type AclRoleState struct {
	// A meaningful name for the role. Must be unique.
	Name pulumi.StringPtrInput
	// A set of rule association objects, documented below.
	Rules AclRoleRuleArrayInput
}

func (AclRoleState) ElementType() reflect.Type {
	return reflect.TypeOf((*aclRoleState)(nil)).Elem()
}

type aclRoleArgs struct {
	// A meaningful name for the role. Must be unique.
	Name *string `pulumi:"name"`
	// A set of rule association objects, documented below.
	Rules []AclRoleRule `pulumi:"rules"`
}

// The set of arguments for constructing a AclRole resource.
type AclRoleArgs struct {
	// A meaningful name for the role. Must be unique.
	Name pulumi.StringPtrInput
	// A set of rule association objects, documented below.
	Rules AclRoleRuleArrayInput
}

func (AclRoleArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*aclRoleArgs)(nil)).Elem()
}

type AclRoleInput interface {
	pulumi.Input

	ToAclRoleOutput() AclRoleOutput
	ToAclRoleOutputWithContext(ctx context.Context) AclRoleOutput
}

func (*AclRole) ElementType() reflect.Type {
	return reflect.TypeOf((**AclRole)(nil)).Elem()
}

func (i *AclRole) ToAclRoleOutput() AclRoleOutput {
	return i.ToAclRoleOutputWithContext(context.Background())
}

func (i *AclRole) ToAclRoleOutputWithContext(ctx context.Context) AclRoleOutput {
	return pulumi.ToOutputWithContext(ctx, i).(AclRoleOutput)
}

func (i *AclRole) ToOutput(ctx context.Context) pulumix.Output[*AclRole] {
	return pulumix.Output[*AclRole]{
		OutputState: i.ToAclRoleOutputWithContext(ctx).OutputState,
	}
}

// AclRoleArrayInput is an input type that accepts AclRoleArray and AclRoleArrayOutput values.
// You can construct a concrete instance of `AclRoleArrayInput` via:
//
//	AclRoleArray{ AclRoleArgs{...} }
type AclRoleArrayInput interface {
	pulumi.Input

	ToAclRoleArrayOutput() AclRoleArrayOutput
	ToAclRoleArrayOutputWithContext(context.Context) AclRoleArrayOutput
}

type AclRoleArray []AclRoleInput

func (AclRoleArray) ElementType() reflect.Type {
	return reflect.TypeOf((*[]*AclRole)(nil)).Elem()
}

func (i AclRoleArray) ToAclRoleArrayOutput() AclRoleArrayOutput {
	return i.ToAclRoleArrayOutputWithContext(context.Background())
}

func (i AclRoleArray) ToAclRoleArrayOutputWithContext(ctx context.Context) AclRoleArrayOutput {
	return pulumi.ToOutputWithContext(ctx, i).(AclRoleArrayOutput)
}

func (i AclRoleArray) ToOutput(ctx context.Context) pulumix.Output[[]*AclRole] {
	return pulumix.Output[[]*AclRole]{
		OutputState: i.ToAclRoleArrayOutputWithContext(ctx).OutputState,
	}
}

// AclRoleMapInput is an input type that accepts AclRoleMap and AclRoleMapOutput values.
// You can construct a concrete instance of `AclRoleMapInput` via:
//
//	AclRoleMap{ "key": AclRoleArgs{...} }
type AclRoleMapInput interface {
	pulumi.Input

	ToAclRoleMapOutput() AclRoleMapOutput
	ToAclRoleMapOutputWithContext(context.Context) AclRoleMapOutput
}

type AclRoleMap map[string]AclRoleInput

func (AclRoleMap) ElementType() reflect.Type {
	return reflect.TypeOf((*map[string]*AclRole)(nil)).Elem()
}

func (i AclRoleMap) ToAclRoleMapOutput() AclRoleMapOutput {
	return i.ToAclRoleMapOutputWithContext(context.Background())
}

func (i AclRoleMap) ToAclRoleMapOutputWithContext(ctx context.Context) AclRoleMapOutput {
	return pulumi.ToOutputWithContext(ctx, i).(AclRoleMapOutput)
}

func (i AclRoleMap) ToOutput(ctx context.Context) pulumix.Output[map[string]*AclRole] {
	return pulumix.Output[map[string]*AclRole]{
		OutputState: i.ToAclRoleMapOutputWithContext(ctx).OutputState,
	}
}

type AclRoleOutput struct{ *pulumi.OutputState }

func (AclRoleOutput) ElementType() reflect.Type {
	return reflect.TypeOf((**AclRole)(nil)).Elem()
}

func (o AclRoleOutput) ToAclRoleOutput() AclRoleOutput {
	return o
}

func (o AclRoleOutput) ToAclRoleOutputWithContext(ctx context.Context) AclRoleOutput {
	return o
}

func (o AclRoleOutput) ToOutput(ctx context.Context) pulumix.Output[*AclRole] {
	return pulumix.Output[*AclRole]{
		OutputState: o.OutputState,
	}
}

// A meaningful name for the role. Must be unique.
func (o AclRoleOutput) Name() pulumi.StringOutput {
	return o.ApplyT(func(v *AclRole) pulumi.StringOutput { return v.Name }).(pulumi.StringOutput)
}

// A set of rule association objects, documented below.
func (o AclRoleOutput) Rules() AclRoleRuleArrayOutput {
	return o.ApplyT(func(v *AclRole) AclRoleRuleArrayOutput { return v.Rules }).(AclRoleRuleArrayOutput)
}

type AclRoleArrayOutput struct{ *pulumi.OutputState }

func (AclRoleArrayOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*[]*AclRole)(nil)).Elem()
}

func (o AclRoleArrayOutput) ToAclRoleArrayOutput() AclRoleArrayOutput {
	return o
}

func (o AclRoleArrayOutput) ToAclRoleArrayOutputWithContext(ctx context.Context) AclRoleArrayOutput {
	return o
}

func (o AclRoleArrayOutput) ToOutput(ctx context.Context) pulumix.Output[[]*AclRole] {
	return pulumix.Output[[]*AclRole]{
		OutputState: o.OutputState,
	}
}

func (o AclRoleArrayOutput) Index(i pulumi.IntInput) AclRoleOutput {
	return pulumi.All(o, i).ApplyT(func(vs []interface{}) *AclRole {
		return vs[0].([]*AclRole)[vs[1].(int)]
	}).(AclRoleOutput)
}

type AclRoleMapOutput struct{ *pulumi.OutputState }

func (AclRoleMapOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*map[string]*AclRole)(nil)).Elem()
}

func (o AclRoleMapOutput) ToAclRoleMapOutput() AclRoleMapOutput {
	return o
}

func (o AclRoleMapOutput) ToAclRoleMapOutputWithContext(ctx context.Context) AclRoleMapOutput {
	return o
}

func (o AclRoleMapOutput) ToOutput(ctx context.Context) pulumix.Output[map[string]*AclRole] {
	return pulumix.Output[map[string]*AclRole]{
		OutputState: o.OutputState,
	}
}

func (o AclRoleMapOutput) MapIndex(k pulumi.StringInput) AclRoleOutput {
	return pulumi.All(o, k).ApplyT(func(vs []interface{}) *AclRole {
		return vs[0].(map[string]*AclRole)[vs[1].(string)]
	}).(AclRoleOutput)
}

func init() {
	pulumi.RegisterInputType(reflect.TypeOf((*AclRoleInput)(nil)).Elem(), &AclRole{})
	pulumi.RegisterInputType(reflect.TypeOf((*AclRoleArrayInput)(nil)).Elem(), AclRoleArray{})
	pulumi.RegisterInputType(reflect.TypeOf((*AclRoleMapInput)(nil)).Elem(), AclRoleMap{})
	pulumi.RegisterOutputType(AclRoleOutput{})
	pulumi.RegisterOutputType(AclRoleArrayOutput{})
	pulumi.RegisterOutputType(AclRoleMapOutput{})
}
