// Code generated by the Pulumi Terraform Bridge (tfgen) Tool DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package rediscloud

import (
	"context"
	"reflect"

	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

// ## Example Usage
//
// ```go
// package main
//
// import (
//
//	"github.com/RedisLabs/pulumi-rediscloud/sdk/go/rediscloud"
//	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
//
// )
//
//	func main() {
//		pulumi.Run(func(ctx *pulumi.Context) error {
//			card, err := rediscloud.GetPaymentMethod(ctx, &rediscloud.GetPaymentMethodArgs{
//				CardType: pulumi.StringRef("Visa"),
//			}, nil)
//			if err != nil {
//				return err
//			}
//			_, err = rediscloud.NewActiveActiveSubscription(ctx, "subscription-resource", &rediscloud.ActiveActiveSubscriptionArgs{
//				PaymentMethodId: *pulumi.String(card.Id),
//				CloudProvider:   pulumi.String("AWS"),
//				CreationPlan: &rediscloud.ActiveActiveSubscriptionCreationPlanArgs{
//					MemoryLimitInGb: pulumi.Float64(1),
//					Quantity:        pulumi.Int(1),
//					Regions: rediscloud.ActiveActiveSubscriptionCreationPlanRegionArray{
//						&rediscloud.ActiveActiveSubscriptionCreationPlanRegionArgs{
//							Region:                   pulumi.String("us-east-1"),
//							NetworkingDeploymentCidr: pulumi.String("192.168.0.0/24"),
//							WriteOperationsPerSecond: pulumi.Int(1000),
//							ReadOperationsPerSecond:  pulumi.Int(1000),
//						},
//						&rediscloud.ActiveActiveSubscriptionCreationPlanRegionArgs{
//							Region:                   pulumi.String("us-east-2"),
//							NetworkingDeploymentCidr: pulumi.String("10.0.1.0/24"),
//							WriteOperationsPerSecond: pulumi.Int(1000),
//							ReadOperationsPerSecond:  pulumi.Int(1000),
//						},
//					},
//				},
//			})
//			if err != nil {
//				return err
//			}
//			return nil
//		})
//	}
//
// ```
//
// ## Import
//
// `rediscloud_active_active_subscription` can be imported using the ID of the subscription, e.g.
//
// ```sh
//
//	$ pulumi import rediscloud:index/activeActiveSubscription:ActiveActiveSubscription subscription-resource 12345678
//
// ```
type ActiveActiveSubscription struct {
	pulumi.CustomResourceState

	// The cloud provider to use with the subscription, (either `AWS` or `GCP`). Default: ‘AWS’
	CloudProvider pulumi.StringPtrOutput `pulumi:"cloudProvider"`
	// A creation plan object, documented below
	CreationPlan ActiveActiveSubscriptionCreationPlanPtrOutput `pulumi:"creationPlan"`
	// A meaningful name to identify the subscription
	Name pulumi.StringOutput `pulumi:"name"`
	// The payment method for the requested subscription, (either `credit-card` or `marketplace`). If `credit-card` is specified, `paymentMethodId` must be defined. Default: 'credit-card'
	PaymentMethod pulumi.StringPtrOutput `pulumi:"paymentMethod"`
	// A valid payment method pre-defined in the current account. This value is __Optional__ for AWS/GCP Marketplace accounts, but __Required__ for all other account types
	PaymentMethodId pulumi.StringOutput `pulumi:"paymentMethodId"`
}

// NewActiveActiveSubscription registers a new resource with the given unique name, arguments, and options.
func NewActiveActiveSubscription(ctx *pulumi.Context,
	name string, args *ActiveActiveSubscriptionArgs, opts ...pulumi.ResourceOption) (*ActiveActiveSubscription, error) {
	if args == nil {
		args = &ActiveActiveSubscriptionArgs{}
	}

	opts = pkgResourceDefaultOpts(opts)
	var resource ActiveActiveSubscription
	err := ctx.RegisterResource("rediscloud:index/activeActiveSubscription:ActiveActiveSubscription", name, args, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// GetActiveActiveSubscription gets an existing ActiveActiveSubscription resource's state with the given name, ID, and optional
// state properties that are used to uniquely qualify the lookup (nil if not required).
func GetActiveActiveSubscription(ctx *pulumi.Context,
	name string, id pulumi.IDInput, state *ActiveActiveSubscriptionState, opts ...pulumi.ResourceOption) (*ActiveActiveSubscription, error) {
	var resource ActiveActiveSubscription
	err := ctx.ReadResource("rediscloud:index/activeActiveSubscription:ActiveActiveSubscription", name, id, state, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// Input properties used for looking up and filtering ActiveActiveSubscription resources.
type activeActiveSubscriptionState struct {
	// The cloud provider to use with the subscription, (either `AWS` or `GCP`). Default: ‘AWS’
	CloudProvider *string `pulumi:"cloudProvider"`
	// A creation plan object, documented below
	CreationPlan *ActiveActiveSubscriptionCreationPlan `pulumi:"creationPlan"`
	// A meaningful name to identify the subscription
	Name *string `pulumi:"name"`
	// The payment method for the requested subscription, (either `credit-card` or `marketplace`). If `credit-card` is specified, `paymentMethodId` must be defined. Default: 'credit-card'
	PaymentMethod *string `pulumi:"paymentMethod"`
	// A valid payment method pre-defined in the current account. This value is __Optional__ for AWS/GCP Marketplace accounts, but __Required__ for all other account types
	PaymentMethodId *string `pulumi:"paymentMethodId"`
}

type ActiveActiveSubscriptionState struct {
	// The cloud provider to use with the subscription, (either `AWS` or `GCP`). Default: ‘AWS’
	CloudProvider pulumi.StringPtrInput
	// A creation plan object, documented below
	CreationPlan ActiveActiveSubscriptionCreationPlanPtrInput
	// A meaningful name to identify the subscription
	Name pulumi.StringPtrInput
	// The payment method for the requested subscription, (either `credit-card` or `marketplace`). If `credit-card` is specified, `paymentMethodId` must be defined. Default: 'credit-card'
	PaymentMethod pulumi.StringPtrInput
	// A valid payment method pre-defined in the current account. This value is __Optional__ for AWS/GCP Marketplace accounts, but __Required__ for all other account types
	PaymentMethodId pulumi.StringPtrInput
}

func (ActiveActiveSubscriptionState) ElementType() reflect.Type {
	return reflect.TypeOf((*activeActiveSubscriptionState)(nil)).Elem()
}

type activeActiveSubscriptionArgs struct {
	// The cloud provider to use with the subscription, (either `AWS` or `GCP`). Default: ‘AWS’
	CloudProvider *string `pulumi:"cloudProvider"`
	// A creation plan object, documented below
	CreationPlan *ActiveActiveSubscriptionCreationPlan `pulumi:"creationPlan"`
	// A meaningful name to identify the subscription
	Name *string `pulumi:"name"`
	// The payment method for the requested subscription, (either `credit-card` or `marketplace`). If `credit-card` is specified, `paymentMethodId` must be defined. Default: 'credit-card'
	PaymentMethod *string `pulumi:"paymentMethod"`
	// A valid payment method pre-defined in the current account. This value is __Optional__ for AWS/GCP Marketplace accounts, but __Required__ for all other account types
	PaymentMethodId *string `pulumi:"paymentMethodId"`
}

// The set of arguments for constructing a ActiveActiveSubscription resource.
type ActiveActiveSubscriptionArgs struct {
	// The cloud provider to use with the subscription, (either `AWS` or `GCP`). Default: ‘AWS’
	CloudProvider pulumi.StringPtrInput
	// A creation plan object, documented below
	CreationPlan ActiveActiveSubscriptionCreationPlanPtrInput
	// A meaningful name to identify the subscription
	Name pulumi.StringPtrInput
	// The payment method for the requested subscription, (either `credit-card` or `marketplace`). If `credit-card` is specified, `paymentMethodId` must be defined. Default: 'credit-card'
	PaymentMethod pulumi.StringPtrInput
	// A valid payment method pre-defined in the current account. This value is __Optional__ for AWS/GCP Marketplace accounts, but __Required__ for all other account types
	PaymentMethodId pulumi.StringPtrInput
}

func (ActiveActiveSubscriptionArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*activeActiveSubscriptionArgs)(nil)).Elem()
}

type ActiveActiveSubscriptionInput interface {
	pulumi.Input

	ToActiveActiveSubscriptionOutput() ActiveActiveSubscriptionOutput
	ToActiveActiveSubscriptionOutputWithContext(ctx context.Context) ActiveActiveSubscriptionOutput
}

func (*ActiveActiveSubscription) ElementType() reflect.Type {
	return reflect.TypeOf((**ActiveActiveSubscription)(nil)).Elem()
}

func (i *ActiveActiveSubscription) ToActiveActiveSubscriptionOutput() ActiveActiveSubscriptionOutput {
	return i.ToActiveActiveSubscriptionOutputWithContext(context.Background())
}

func (i *ActiveActiveSubscription) ToActiveActiveSubscriptionOutputWithContext(ctx context.Context) ActiveActiveSubscriptionOutput {
	return pulumi.ToOutputWithContext(ctx, i).(ActiveActiveSubscriptionOutput)
}

// ActiveActiveSubscriptionArrayInput is an input type that accepts ActiveActiveSubscriptionArray and ActiveActiveSubscriptionArrayOutput values.
// You can construct a concrete instance of `ActiveActiveSubscriptionArrayInput` via:
//
//	ActiveActiveSubscriptionArray{ ActiveActiveSubscriptionArgs{...} }
type ActiveActiveSubscriptionArrayInput interface {
	pulumi.Input

	ToActiveActiveSubscriptionArrayOutput() ActiveActiveSubscriptionArrayOutput
	ToActiveActiveSubscriptionArrayOutputWithContext(context.Context) ActiveActiveSubscriptionArrayOutput
}

type ActiveActiveSubscriptionArray []ActiveActiveSubscriptionInput

func (ActiveActiveSubscriptionArray) ElementType() reflect.Type {
	return reflect.TypeOf((*[]*ActiveActiveSubscription)(nil)).Elem()
}

func (i ActiveActiveSubscriptionArray) ToActiveActiveSubscriptionArrayOutput() ActiveActiveSubscriptionArrayOutput {
	return i.ToActiveActiveSubscriptionArrayOutputWithContext(context.Background())
}

func (i ActiveActiveSubscriptionArray) ToActiveActiveSubscriptionArrayOutputWithContext(ctx context.Context) ActiveActiveSubscriptionArrayOutput {
	return pulumi.ToOutputWithContext(ctx, i).(ActiveActiveSubscriptionArrayOutput)
}

// ActiveActiveSubscriptionMapInput is an input type that accepts ActiveActiveSubscriptionMap and ActiveActiveSubscriptionMapOutput values.
// You can construct a concrete instance of `ActiveActiveSubscriptionMapInput` via:
//
//	ActiveActiveSubscriptionMap{ "key": ActiveActiveSubscriptionArgs{...} }
type ActiveActiveSubscriptionMapInput interface {
	pulumi.Input

	ToActiveActiveSubscriptionMapOutput() ActiveActiveSubscriptionMapOutput
	ToActiveActiveSubscriptionMapOutputWithContext(context.Context) ActiveActiveSubscriptionMapOutput
}

type ActiveActiveSubscriptionMap map[string]ActiveActiveSubscriptionInput

func (ActiveActiveSubscriptionMap) ElementType() reflect.Type {
	return reflect.TypeOf((*map[string]*ActiveActiveSubscription)(nil)).Elem()
}

func (i ActiveActiveSubscriptionMap) ToActiveActiveSubscriptionMapOutput() ActiveActiveSubscriptionMapOutput {
	return i.ToActiveActiveSubscriptionMapOutputWithContext(context.Background())
}

func (i ActiveActiveSubscriptionMap) ToActiveActiveSubscriptionMapOutputWithContext(ctx context.Context) ActiveActiveSubscriptionMapOutput {
	return pulumi.ToOutputWithContext(ctx, i).(ActiveActiveSubscriptionMapOutput)
}

type ActiveActiveSubscriptionOutput struct{ *pulumi.OutputState }

func (ActiveActiveSubscriptionOutput) ElementType() reflect.Type {
	return reflect.TypeOf((**ActiveActiveSubscription)(nil)).Elem()
}

func (o ActiveActiveSubscriptionOutput) ToActiveActiveSubscriptionOutput() ActiveActiveSubscriptionOutput {
	return o
}

func (o ActiveActiveSubscriptionOutput) ToActiveActiveSubscriptionOutputWithContext(ctx context.Context) ActiveActiveSubscriptionOutput {
	return o
}

// The cloud provider to use with the subscription, (either `AWS` or `GCP`). Default: ‘AWS’
func (o ActiveActiveSubscriptionOutput) CloudProvider() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *ActiveActiveSubscription) pulumi.StringPtrOutput { return v.CloudProvider }).(pulumi.StringPtrOutput)
}

// A creation plan object, documented below
func (o ActiveActiveSubscriptionOutput) CreationPlan() ActiveActiveSubscriptionCreationPlanPtrOutput {
	return o.ApplyT(func(v *ActiveActiveSubscription) ActiveActiveSubscriptionCreationPlanPtrOutput { return v.CreationPlan }).(ActiveActiveSubscriptionCreationPlanPtrOutput)
}

// A meaningful name to identify the subscription
func (o ActiveActiveSubscriptionOutput) Name() pulumi.StringOutput {
	return o.ApplyT(func(v *ActiveActiveSubscription) pulumi.StringOutput { return v.Name }).(pulumi.StringOutput)
}

// The payment method for the requested subscription, (either `credit-card` or `marketplace`). If `credit-card` is specified, `paymentMethodId` must be defined. Default: 'credit-card'
func (o ActiveActiveSubscriptionOutput) PaymentMethod() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *ActiveActiveSubscription) pulumi.StringPtrOutput { return v.PaymentMethod }).(pulumi.StringPtrOutput)
}

// A valid payment method pre-defined in the current account. This value is __Optional__ for AWS/GCP Marketplace accounts, but __Required__ for all other account types
func (o ActiveActiveSubscriptionOutput) PaymentMethodId() pulumi.StringOutput {
	return o.ApplyT(func(v *ActiveActiveSubscription) pulumi.StringOutput { return v.PaymentMethodId }).(pulumi.StringOutput)
}

type ActiveActiveSubscriptionArrayOutput struct{ *pulumi.OutputState }

func (ActiveActiveSubscriptionArrayOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*[]*ActiveActiveSubscription)(nil)).Elem()
}

func (o ActiveActiveSubscriptionArrayOutput) ToActiveActiveSubscriptionArrayOutput() ActiveActiveSubscriptionArrayOutput {
	return o
}

func (o ActiveActiveSubscriptionArrayOutput) ToActiveActiveSubscriptionArrayOutputWithContext(ctx context.Context) ActiveActiveSubscriptionArrayOutput {
	return o
}

func (o ActiveActiveSubscriptionArrayOutput) Index(i pulumi.IntInput) ActiveActiveSubscriptionOutput {
	return pulumi.All(o, i).ApplyT(func(vs []interface{}) *ActiveActiveSubscription {
		return vs[0].([]*ActiveActiveSubscription)[vs[1].(int)]
	}).(ActiveActiveSubscriptionOutput)
}

type ActiveActiveSubscriptionMapOutput struct{ *pulumi.OutputState }

func (ActiveActiveSubscriptionMapOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*map[string]*ActiveActiveSubscription)(nil)).Elem()
}

func (o ActiveActiveSubscriptionMapOutput) ToActiveActiveSubscriptionMapOutput() ActiveActiveSubscriptionMapOutput {
	return o
}

func (o ActiveActiveSubscriptionMapOutput) ToActiveActiveSubscriptionMapOutputWithContext(ctx context.Context) ActiveActiveSubscriptionMapOutput {
	return o
}

func (o ActiveActiveSubscriptionMapOutput) MapIndex(k pulumi.StringInput) ActiveActiveSubscriptionOutput {
	return pulumi.All(o, k).ApplyT(func(vs []interface{}) *ActiveActiveSubscription {
		return vs[0].(map[string]*ActiveActiveSubscription)[vs[1].(string)]
	}).(ActiveActiveSubscriptionOutput)
}

func init() {
	pulumi.RegisterInputType(reflect.TypeOf((*ActiveActiveSubscriptionInput)(nil)).Elem(), &ActiveActiveSubscription{})
	pulumi.RegisterInputType(reflect.TypeOf((*ActiveActiveSubscriptionArrayInput)(nil)).Elem(), ActiveActiveSubscriptionArray{})
	pulumi.RegisterInputType(reflect.TypeOf((*ActiveActiveSubscriptionMapInput)(nil)).Elem(), ActiveActiveSubscriptionMap{})
	pulumi.RegisterOutputType(ActiveActiveSubscriptionOutput{})
	pulumi.RegisterOutputType(ActiveActiveSubscriptionArrayOutput{})
	pulumi.RegisterOutputType(ActiveActiveSubscriptionMapOutput{})
}
