// Code generated by the Pulumi Terraform Bridge (tfgen) Tool DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package rediscloud

import (
	"context"
	"reflect"

	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

func LookupCloudAccount(ctx *pulumi.Context, args *LookupCloudAccountArgs, opts ...pulumi.InvokeOption) (*LookupCloudAccountResult, error) {
	var rv LookupCloudAccountResult
	err := ctx.Invoke("rediscloud:index/getCloudAccount:getCloudAccount", args, &rv, opts...)
	if err != nil {
		return nil, err
	}
	return &rv, nil
}

// A collection of arguments for invoking getCloudAccount.
type LookupCloudAccountArgs struct {
	ExcludeInternalAccount *bool   `pulumi:"excludeInternalAccount"`
	Name                   *string `pulumi:"name"`
	ProviderType           *string `pulumi:"providerType"`
}

// A collection of values returned by getCloudAccount.
type LookupCloudAccountResult struct {
	AccessKeyId            string `pulumi:"accessKeyId"`
	ExcludeInternalAccount *bool  `pulumi:"excludeInternalAccount"`
	// The provider-assigned unique ID for this managed resource.
	Id           string `pulumi:"id"`
	Name         string `pulumi:"name"`
	ProviderType string `pulumi:"providerType"`
}

func LookupCloudAccountOutput(ctx *pulumi.Context, args LookupCloudAccountOutputArgs, opts ...pulumi.InvokeOption) LookupCloudAccountResultOutput {
	return pulumi.ToOutputWithContext(context.Background(), args).
		ApplyT(func(v interface{}) (LookupCloudAccountResult, error) {
			args := v.(LookupCloudAccountArgs)
			r, err := LookupCloudAccount(ctx, &args, opts...)
			var s LookupCloudAccountResult
			if r != nil {
				s = *r
			}
			return s, err
		}).(LookupCloudAccountResultOutput)
}

// A collection of arguments for invoking getCloudAccount.
type LookupCloudAccountOutputArgs struct {
	ExcludeInternalAccount pulumi.BoolPtrInput   `pulumi:"excludeInternalAccount"`
	Name                   pulumi.StringPtrInput `pulumi:"name"`
	ProviderType           pulumi.StringPtrInput `pulumi:"providerType"`
}

func (LookupCloudAccountOutputArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*LookupCloudAccountArgs)(nil)).Elem()
}

// A collection of values returned by getCloudAccount.
type LookupCloudAccountResultOutput struct{ *pulumi.OutputState }

func (LookupCloudAccountResultOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*LookupCloudAccountResult)(nil)).Elem()
}

func (o LookupCloudAccountResultOutput) ToLookupCloudAccountResultOutput() LookupCloudAccountResultOutput {
	return o
}

func (o LookupCloudAccountResultOutput) ToLookupCloudAccountResultOutputWithContext(ctx context.Context) LookupCloudAccountResultOutput {
	return o
}

func (o LookupCloudAccountResultOutput) AccessKeyId() pulumi.StringOutput {
	return o.ApplyT(func(v LookupCloudAccountResult) string { return v.AccessKeyId }).(pulumi.StringOutput)
}

func (o LookupCloudAccountResultOutput) ExcludeInternalAccount() pulumi.BoolPtrOutput {
	return o.ApplyT(func(v LookupCloudAccountResult) *bool { return v.ExcludeInternalAccount }).(pulumi.BoolPtrOutput)
}

// The provider-assigned unique ID for this managed resource.
func (o LookupCloudAccountResultOutput) Id() pulumi.StringOutput {
	return o.ApplyT(func(v LookupCloudAccountResult) string { return v.Id }).(pulumi.StringOutput)
}

func (o LookupCloudAccountResultOutput) Name() pulumi.StringOutput {
	return o.ApplyT(func(v LookupCloudAccountResult) string { return v.Name }).(pulumi.StringOutput)
}

func (o LookupCloudAccountResultOutput) ProviderType() pulumi.StringOutput {
	return o.ApplyT(func(v LookupCloudAccountResult) string { return v.ProviderType }).(pulumi.StringOutput)
}

func init() {
	pulumi.RegisterOutputType(LookupCloudAccountResultOutput{})
}
