// Code generated by the Pulumi Terraform Bridge (tfgen) Tool DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package rediscloud

import (
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

func GetDataPersistence(ctx *pulumi.Context, opts ...pulumi.InvokeOption) (*GetDataPersistenceResult, error) {
	var rv GetDataPersistenceResult
	err := ctx.Invoke("rediscloud:index/getDataPersistence:getDataPersistence", nil, &rv, opts...)
	if err != nil {
		return nil, err
	}
	return &rv, nil
}

// A collection of values returned by getDataPersistence.
type GetDataPersistenceResult struct {
	DataPersistences []GetDataPersistenceDataPersistence `pulumi:"dataPersistences"`
	// The provider-assigned unique ID for this managed resource.
	Id string `pulumi:"id"`
}
