// Code generated by the Pulumi Terraform Bridge (tfgen) Tool DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package rediscloud

import (
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

func GetDatabaseModules(ctx *pulumi.Context, opts ...pulumi.InvokeOption) (*GetDatabaseModulesResult, error) {
	var rv GetDatabaseModulesResult
	err := ctx.Invoke("rediscloud:index/getDatabaseModules:getDatabaseModules", nil, &rv, opts...)
	if err != nil {
		return nil, err
	}
	return &rv, nil
}

// A collection of values returned by getDatabaseModules.
type GetDatabaseModulesResult struct {
	// The provider-assigned unique ID for this managed resource.
	Id      string                     `pulumi:"id"`
	Modules []GetDatabaseModulesModule `pulumi:"modules"`
}
