// Code generated by the Pulumi Terraform Bridge (tfgen) Tool DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package rediscloud

import (
	"context"
	"reflect"

	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

func GetDatabase(ctx *pulumi.Context, args *GetDatabaseArgs, opts ...pulumi.InvokeOption) (*GetDatabaseResult, error) {
	var rv GetDatabaseResult
	err := ctx.Invoke("rediscloud:index/getDatabase:getDatabase", args, &rv, opts...)
	if err != nil {
		return nil, err
	}
	return &rv, nil
}

// A collection of arguments for invoking getDatabase.
type GetDatabaseArgs struct {
	Name           *string `pulumi:"name"`
	Protocol       *string `pulumi:"protocol"`
	Region         *string `pulumi:"region"`
	SubscriptionId string  `pulumi:"subscriptionId"`
}

// A collection of values returned by getDatabase.
type GetDatabaseResult struct {
	Alerts          []GetDatabaseAlert `pulumi:"alerts"`
	DataEviction    string             `pulumi:"dataEviction"`
	DataPersistence string             `pulumi:"dataPersistence"`
	HashingPolicies []string           `pulumi:"hashingPolicies"`
	// The provider-assigned unique ID for this managed resource.
	Id                         string              `pulumi:"id"`
	MemoryLimitInGb            float64             `pulumi:"memoryLimitInGb"`
	Modules                    []GetDatabaseModule `pulumi:"modules"`
	Name                       string              `pulumi:"name"`
	Password                   string              `pulumi:"password"`
	PrivateEndpoint            string              `pulumi:"privateEndpoint"`
	Protocol                   string              `pulumi:"protocol"`
	PublicEndpoint             string              `pulumi:"publicEndpoint"`
	Region                     string              `pulumi:"region"`
	ReplicaOfs                 []string            `pulumi:"replicaOfs"`
	Replication                bool                `pulumi:"replication"`
	SubscriptionId             string              `pulumi:"subscriptionId"`
	SupportOssClusterApi       bool                `pulumi:"supportOssClusterApi"`
	ThroughputMeasurementBy    string              `pulumi:"throughputMeasurementBy"`
	ThroughputMeasurementValue int                 `pulumi:"throughputMeasurementValue"`
}

func GetDatabaseOutput(ctx *pulumi.Context, args GetDatabaseOutputArgs, opts ...pulumi.InvokeOption) GetDatabaseResultOutput {
	return pulumi.ToOutputWithContext(context.Background(), args).
		ApplyT(func(v interface{}) (GetDatabaseResult, error) {
			args := v.(GetDatabaseArgs)
			r, err := GetDatabase(ctx, &args, opts...)
			var s GetDatabaseResult
			if r != nil {
				s = *r
			}
			return s, err
		}).(GetDatabaseResultOutput)
}

// A collection of arguments for invoking getDatabase.
type GetDatabaseOutputArgs struct {
	Name           pulumi.StringPtrInput `pulumi:"name"`
	Protocol       pulumi.StringPtrInput `pulumi:"protocol"`
	Region         pulumi.StringPtrInput `pulumi:"region"`
	SubscriptionId pulumi.StringInput    `pulumi:"subscriptionId"`
}

func (GetDatabaseOutputArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*GetDatabaseArgs)(nil)).Elem()
}

// A collection of values returned by getDatabase.
type GetDatabaseResultOutput struct{ *pulumi.OutputState }

func (GetDatabaseResultOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*GetDatabaseResult)(nil)).Elem()
}

func (o GetDatabaseResultOutput) ToGetDatabaseResultOutput() GetDatabaseResultOutput {
	return o
}

func (o GetDatabaseResultOutput) ToGetDatabaseResultOutputWithContext(ctx context.Context) GetDatabaseResultOutput {
	return o
}

func (o GetDatabaseResultOutput) Alerts() GetDatabaseAlertArrayOutput {
	return o.ApplyT(func(v GetDatabaseResult) []GetDatabaseAlert { return v.Alerts }).(GetDatabaseAlertArrayOutput)
}

func (o GetDatabaseResultOutput) DataEviction() pulumi.StringOutput {
	return o.ApplyT(func(v GetDatabaseResult) string { return v.DataEviction }).(pulumi.StringOutput)
}

func (o GetDatabaseResultOutput) DataPersistence() pulumi.StringOutput {
	return o.ApplyT(func(v GetDatabaseResult) string { return v.DataPersistence }).(pulumi.StringOutput)
}

func (o GetDatabaseResultOutput) HashingPolicies() pulumi.StringArrayOutput {
	return o.ApplyT(func(v GetDatabaseResult) []string { return v.HashingPolicies }).(pulumi.StringArrayOutput)
}

// The provider-assigned unique ID for this managed resource.
func (o GetDatabaseResultOutput) Id() pulumi.StringOutput {
	return o.ApplyT(func(v GetDatabaseResult) string { return v.Id }).(pulumi.StringOutput)
}

func (o GetDatabaseResultOutput) MemoryLimitInGb() pulumi.Float64Output {
	return o.ApplyT(func(v GetDatabaseResult) float64 { return v.MemoryLimitInGb }).(pulumi.Float64Output)
}

func (o GetDatabaseResultOutput) Modules() GetDatabaseModuleArrayOutput {
	return o.ApplyT(func(v GetDatabaseResult) []GetDatabaseModule { return v.Modules }).(GetDatabaseModuleArrayOutput)
}

func (o GetDatabaseResultOutput) Name() pulumi.StringOutput {
	return o.ApplyT(func(v GetDatabaseResult) string { return v.Name }).(pulumi.StringOutput)
}

func (o GetDatabaseResultOutput) Password() pulumi.StringOutput {
	return o.ApplyT(func(v GetDatabaseResult) string { return v.Password }).(pulumi.StringOutput)
}

func (o GetDatabaseResultOutput) PrivateEndpoint() pulumi.StringOutput {
	return o.ApplyT(func(v GetDatabaseResult) string { return v.PrivateEndpoint }).(pulumi.StringOutput)
}

func (o GetDatabaseResultOutput) Protocol() pulumi.StringOutput {
	return o.ApplyT(func(v GetDatabaseResult) string { return v.Protocol }).(pulumi.StringOutput)
}

func (o GetDatabaseResultOutput) PublicEndpoint() pulumi.StringOutput {
	return o.ApplyT(func(v GetDatabaseResult) string { return v.PublicEndpoint }).(pulumi.StringOutput)
}

func (o GetDatabaseResultOutput) Region() pulumi.StringOutput {
	return o.ApplyT(func(v GetDatabaseResult) string { return v.Region }).(pulumi.StringOutput)
}

func (o GetDatabaseResultOutput) ReplicaOfs() pulumi.StringArrayOutput {
	return o.ApplyT(func(v GetDatabaseResult) []string { return v.ReplicaOfs }).(pulumi.StringArrayOutput)
}

func (o GetDatabaseResultOutput) Replication() pulumi.BoolOutput {
	return o.ApplyT(func(v GetDatabaseResult) bool { return v.Replication }).(pulumi.BoolOutput)
}

func (o GetDatabaseResultOutput) SubscriptionId() pulumi.StringOutput {
	return o.ApplyT(func(v GetDatabaseResult) string { return v.SubscriptionId }).(pulumi.StringOutput)
}

func (o GetDatabaseResultOutput) SupportOssClusterApi() pulumi.BoolOutput {
	return o.ApplyT(func(v GetDatabaseResult) bool { return v.SupportOssClusterApi }).(pulumi.BoolOutput)
}

func (o GetDatabaseResultOutput) ThroughputMeasurementBy() pulumi.StringOutput {
	return o.ApplyT(func(v GetDatabaseResult) string { return v.ThroughputMeasurementBy }).(pulumi.StringOutput)
}

func (o GetDatabaseResultOutput) ThroughputMeasurementValue() pulumi.IntOutput {
	return o.ApplyT(func(v GetDatabaseResult) int { return v.ThroughputMeasurementValue }).(pulumi.IntOutput)
}

func init() {
	pulumi.RegisterOutputType(GetDatabaseResultOutput{})
}
