// Code generated by the Pulumi Terraform Bridge (tfgen) Tool DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package rediscloud

import (
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

// The database modules data source allows access to a list of supported [Redis Enterprise Cloud modules](https://redislabs.com/redis-enterprise/modules).\
// Each module represents an enrichment that can be applied to a Redis database.
//
// ## Example Usage
//
// The following example returns a list of all modules available within your Redis Enterprise Cloud account.
//
// ```go
// package main
//
// import (
//
//	"github.com/RedisLabs/pulumi-rediscloud/sdk/go/rediscloud"
//	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
//
// )
//
//	func main() {
//		pulumi.Run(func(ctx *pulumi.Context) error {
//			example, err := rediscloud.GetDatabaseModules(ctx, nil, nil)
//			if err != nil {
//				return err
//			}
//			ctx.Export("rediscloudDatabaseModules", example.Modules)
//			return nil
//		})
//	}
//
// ```
func GetDatabaseModules(ctx *pulumi.Context, opts ...pulumi.InvokeOption) (*GetDatabaseModulesResult, error) {
	opts = pkgInvokeDefaultOpts(opts)
	var rv GetDatabaseModulesResult
	err := ctx.Invoke("rediscloud:index/getDatabaseModules:getDatabaseModules", nil, &rv, opts...)
	if err != nil {
		return nil, err
	}
	return &rv, nil
}

// A collection of values returned by getDatabaseModules.
type GetDatabaseModulesResult struct {
	// The provider-assigned unique ID for this managed resource.
	Id string `pulumi:"id"`
	// A list of database modules.
	Modules []GetDatabaseModulesModule `pulumi:"modules"`
}
