// Code generated by the Pulumi Terraform Bridge (tfgen) Tool DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package rediscloud

import (
	"context"
	"reflect"

	"github.com/RedisLabs/pulumi-rediscloud/sdk/go/rediscloud/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumix"
)

// The Payment Method data source allows access to the ID of a Payment Method configured against your Redis Enterprise Cloud account. This ID can be used when creating Subscription resources.
func GetPaymentMethod(ctx *pulumi.Context, args *GetPaymentMethodArgs, opts ...pulumi.InvokeOption) (*GetPaymentMethodResult, error) {
	opts = internal.PkgInvokeDefaultOpts(opts)
	var rv GetPaymentMethodResult
	err := ctx.Invoke("rediscloud:index/getPaymentMethod:getPaymentMethod", args, &rv, opts...)
	if err != nil {
		return nil, err
	}
	return &rv, nil
}

// A collection of arguments for invoking getPaymentMethod.
type GetPaymentMethodArgs struct {
	// Type of card that the payment method should be, such as `Visa`.
	CardType *string `pulumi:"cardType"`
	// Whether to exclude any expired cards or not. Default is `true`.
	ExcludeExpired *bool `pulumi:"excludeExpired"`
	// Last four numbers of the card of the payment method.
	LastFourNumbers *string `pulumi:"lastFourNumbers"`
}

// A collection of values returned by getPaymentMethod.
type GetPaymentMethodResult struct {
	CardType       string `pulumi:"cardType"`
	ExcludeExpired *bool  `pulumi:"excludeExpired"`
	// The provider-assigned unique ID for this managed resource.
	Id              string `pulumi:"id"`
	LastFourNumbers string `pulumi:"lastFourNumbers"`
}

func GetPaymentMethodOutput(ctx *pulumi.Context, args GetPaymentMethodOutputArgs, opts ...pulumi.InvokeOption) GetPaymentMethodResultOutput {
	return pulumi.ToOutputWithContext(context.Background(), args).
		ApplyT(func(v interface{}) (GetPaymentMethodResult, error) {
			args := v.(GetPaymentMethodArgs)
			r, err := GetPaymentMethod(ctx, &args, opts...)
			var s GetPaymentMethodResult
			if r != nil {
				s = *r
			}
			return s, err
		}).(GetPaymentMethodResultOutput)
}

// A collection of arguments for invoking getPaymentMethod.
type GetPaymentMethodOutputArgs struct {
	// Type of card that the payment method should be, such as `Visa`.
	CardType pulumi.StringPtrInput `pulumi:"cardType"`
	// Whether to exclude any expired cards or not. Default is `true`.
	ExcludeExpired pulumi.BoolPtrInput `pulumi:"excludeExpired"`
	// Last four numbers of the card of the payment method.
	LastFourNumbers pulumi.StringPtrInput `pulumi:"lastFourNumbers"`
}

func (GetPaymentMethodOutputArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*GetPaymentMethodArgs)(nil)).Elem()
}

// A collection of values returned by getPaymentMethod.
type GetPaymentMethodResultOutput struct{ *pulumi.OutputState }

func (GetPaymentMethodResultOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*GetPaymentMethodResult)(nil)).Elem()
}

func (o GetPaymentMethodResultOutput) ToGetPaymentMethodResultOutput() GetPaymentMethodResultOutput {
	return o
}

func (o GetPaymentMethodResultOutput) ToGetPaymentMethodResultOutputWithContext(ctx context.Context) GetPaymentMethodResultOutput {
	return o
}

func (o GetPaymentMethodResultOutput) ToOutput(ctx context.Context) pulumix.Output[GetPaymentMethodResult] {
	return pulumix.Output[GetPaymentMethodResult]{
		OutputState: o.OutputState,
	}
}

func (o GetPaymentMethodResultOutput) CardType() pulumi.StringOutput {
	return o.ApplyT(func(v GetPaymentMethodResult) string { return v.CardType }).(pulumi.StringOutput)
}

func (o GetPaymentMethodResultOutput) ExcludeExpired() pulumi.BoolPtrOutput {
	return o.ApplyT(func(v GetPaymentMethodResult) *bool { return v.ExcludeExpired }).(pulumi.BoolPtrOutput)
}

// The provider-assigned unique ID for this managed resource.
func (o GetPaymentMethodResultOutput) Id() pulumi.StringOutput {
	return o.ApplyT(func(v GetPaymentMethodResult) string { return v.Id }).(pulumi.StringOutput)
}

func (o GetPaymentMethodResultOutput) LastFourNumbers() pulumi.StringOutput {
	return o.ApplyT(func(v GetPaymentMethodResult) string { return v.LastFourNumbers }).(pulumi.StringOutput)
}

func init() {
	pulumi.RegisterOutputType(GetPaymentMethodResultOutput{})
}
