// Code generated by the Pulumi Terraform Bridge (tfgen) Tool DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package rediscloud

import (
	"context"
	"reflect"

	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

func LookupSubscription(ctx *pulumi.Context, args *LookupSubscriptionArgs, opts ...pulumi.InvokeOption) (*LookupSubscriptionResult, error) {
	var rv LookupSubscriptionResult
	err := ctx.Invoke("rediscloud:index/getSubscription:getSubscription", args, &rv, opts...)
	if err != nil {
		return nil, err
	}
	return &rv, nil
}

// A collection of arguments for invoking getSubscription.
type LookupSubscriptionArgs struct {
	Name *string `pulumi:"name"`
}

// A collection of values returned by getSubscription.
type LookupSubscriptionResult struct {
	CloudProviders []GetSubscriptionCloudProvider `pulumi:"cloudProviders"`
	// The provider-assigned unique ID for this managed resource.
	Id                string `pulumi:"id"`
	MemoryStorage     string `pulumi:"memoryStorage"`
	Name              string `pulumi:"name"`
	NumberOfDatabases int    `pulumi:"numberOfDatabases"`
	PaymentMethod     string `pulumi:"paymentMethod"`
	PaymentMethodId   string `pulumi:"paymentMethodId"`
	Status            string `pulumi:"status"`
}

func LookupSubscriptionOutput(ctx *pulumi.Context, args LookupSubscriptionOutputArgs, opts ...pulumi.InvokeOption) LookupSubscriptionResultOutput {
	return pulumi.ToOutputWithContext(context.Background(), args).
		ApplyT(func(v interface{}) (LookupSubscriptionResult, error) {
			args := v.(LookupSubscriptionArgs)
			r, err := LookupSubscription(ctx, &args, opts...)
			var s LookupSubscriptionResult
			if r != nil {
				s = *r
			}
			return s, err
		}).(LookupSubscriptionResultOutput)
}

// A collection of arguments for invoking getSubscription.
type LookupSubscriptionOutputArgs struct {
	Name pulumi.StringPtrInput `pulumi:"name"`
}

func (LookupSubscriptionOutputArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*LookupSubscriptionArgs)(nil)).Elem()
}

// A collection of values returned by getSubscription.
type LookupSubscriptionResultOutput struct{ *pulumi.OutputState }

func (LookupSubscriptionResultOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*LookupSubscriptionResult)(nil)).Elem()
}

func (o LookupSubscriptionResultOutput) ToLookupSubscriptionResultOutput() LookupSubscriptionResultOutput {
	return o
}

func (o LookupSubscriptionResultOutput) ToLookupSubscriptionResultOutputWithContext(ctx context.Context) LookupSubscriptionResultOutput {
	return o
}

func (o LookupSubscriptionResultOutput) CloudProviders() GetSubscriptionCloudProviderArrayOutput {
	return o.ApplyT(func(v LookupSubscriptionResult) []GetSubscriptionCloudProvider { return v.CloudProviders }).(GetSubscriptionCloudProviderArrayOutput)
}

// The provider-assigned unique ID for this managed resource.
func (o LookupSubscriptionResultOutput) Id() pulumi.StringOutput {
	return o.ApplyT(func(v LookupSubscriptionResult) string { return v.Id }).(pulumi.StringOutput)
}

func (o LookupSubscriptionResultOutput) MemoryStorage() pulumi.StringOutput {
	return o.ApplyT(func(v LookupSubscriptionResult) string { return v.MemoryStorage }).(pulumi.StringOutput)
}

func (o LookupSubscriptionResultOutput) Name() pulumi.StringOutput {
	return o.ApplyT(func(v LookupSubscriptionResult) string { return v.Name }).(pulumi.StringOutput)
}

func (o LookupSubscriptionResultOutput) NumberOfDatabases() pulumi.IntOutput {
	return o.ApplyT(func(v LookupSubscriptionResult) int { return v.NumberOfDatabases }).(pulumi.IntOutput)
}

func (o LookupSubscriptionResultOutput) PaymentMethod() pulumi.StringOutput {
	return o.ApplyT(func(v LookupSubscriptionResult) string { return v.PaymentMethod }).(pulumi.StringOutput)
}

func (o LookupSubscriptionResultOutput) PaymentMethodId() pulumi.StringOutput {
	return o.ApplyT(func(v LookupSubscriptionResult) string { return v.PaymentMethodId }).(pulumi.StringOutput)
}

func (o LookupSubscriptionResultOutput) Status() pulumi.StringOutput {
	return o.ApplyT(func(v LookupSubscriptionResult) string { return v.Status }).(pulumi.StringOutput)
}

func init() {
	pulumi.RegisterOutputType(LookupSubscriptionResultOutput{})
}
