// Code generated by the Pulumi Terraform Bridge (tfgen) Tool DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package rediscloud

import (
	"context"
	"reflect"

	"github.com/pkg/errors"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

type Subscription struct {
	pulumi.CustomResourceState

	// An allowlist object
	Allowlist SubscriptionAllowlistPtrOutput `pulumi:"allowlist"`
	// A cloud provider object
	CloudProvider SubscriptionCloudProviderOutput `pulumi:"cloudProvider"`
	// Information about the planned databases used to optimise the database infrastructure. This information is only used when
	// creating a new subscription and any changes will be ignored after this.
	CreationPlan SubscriptionCreationPlanPtrOutput `pulumi:"creationPlan"`
	// Memory storage preference: either ‘ram’ or a combination of 'ram-and-flash’
	MemoryStorage pulumi.StringPtrOutput `pulumi:"memoryStorage"`
	// A meaningful name to identify the subscription
	Name pulumi.StringOutput `pulumi:"name"`
	// Payment method for the requested subscription. If credit card is specified, the payment method Id must be defined.
	PaymentMethod pulumi.StringPtrOutput `pulumi:"paymentMethod"`
	// A valid payment method pre-defined in the current account
	PaymentMethodId pulumi.StringOutput `pulumi:"paymentMethodId"`
}

// NewSubscription registers a new resource with the given unique name, arguments, and options.
func NewSubscription(ctx *pulumi.Context,
	name string, args *SubscriptionArgs, opts ...pulumi.ResourceOption) (*Subscription, error) {
	if args == nil {
		return nil, errors.New("missing one or more required arguments")
	}

	if args.CloudProvider == nil {
		return nil, errors.New("invalid value for required argument 'CloudProvider'")
	}
	var resource Subscription
	err := ctx.RegisterResource("rediscloud:index/subscription:Subscription", name, args, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// GetSubscription gets an existing Subscription resource's state with the given name, ID, and optional
// state properties that are used to uniquely qualify the lookup (nil if not required).
func GetSubscription(ctx *pulumi.Context,
	name string, id pulumi.IDInput, state *SubscriptionState, opts ...pulumi.ResourceOption) (*Subscription, error) {
	var resource Subscription
	err := ctx.ReadResource("rediscloud:index/subscription:Subscription", name, id, state, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// Input properties used for looking up and filtering Subscription resources.
type subscriptionState struct {
	// An allowlist object
	Allowlist *SubscriptionAllowlist `pulumi:"allowlist"`
	// A cloud provider object
	CloudProvider *SubscriptionCloudProvider `pulumi:"cloudProvider"`
	// Information about the planned databases used to optimise the database infrastructure. This information is only used when
	// creating a new subscription and any changes will be ignored after this.
	CreationPlan *SubscriptionCreationPlan `pulumi:"creationPlan"`
	// Memory storage preference: either ‘ram’ or a combination of 'ram-and-flash’
	MemoryStorage *string `pulumi:"memoryStorage"`
	// A meaningful name to identify the subscription
	Name *string `pulumi:"name"`
	// Payment method for the requested subscription. If credit card is specified, the payment method Id must be defined.
	PaymentMethod *string `pulumi:"paymentMethod"`
	// A valid payment method pre-defined in the current account
	PaymentMethodId *string `pulumi:"paymentMethodId"`
}

type SubscriptionState struct {
	// An allowlist object
	Allowlist SubscriptionAllowlistPtrInput
	// A cloud provider object
	CloudProvider SubscriptionCloudProviderPtrInput
	// Information about the planned databases used to optimise the database infrastructure. This information is only used when
	// creating a new subscription and any changes will be ignored after this.
	CreationPlan SubscriptionCreationPlanPtrInput
	// Memory storage preference: either ‘ram’ or a combination of 'ram-and-flash’
	MemoryStorage pulumi.StringPtrInput
	// A meaningful name to identify the subscription
	Name pulumi.StringPtrInput
	// Payment method for the requested subscription. If credit card is specified, the payment method Id must be defined.
	PaymentMethod pulumi.StringPtrInput
	// A valid payment method pre-defined in the current account
	PaymentMethodId pulumi.StringPtrInput
}

func (SubscriptionState) ElementType() reflect.Type {
	return reflect.TypeOf((*subscriptionState)(nil)).Elem()
}

type subscriptionArgs struct {
	// An allowlist object
	Allowlist *SubscriptionAllowlist `pulumi:"allowlist"`
	// A cloud provider object
	CloudProvider SubscriptionCloudProvider `pulumi:"cloudProvider"`
	// Information about the planned databases used to optimise the database infrastructure. This information is only used when
	// creating a new subscription and any changes will be ignored after this.
	CreationPlan *SubscriptionCreationPlan `pulumi:"creationPlan"`
	// Memory storage preference: either ‘ram’ or a combination of 'ram-and-flash’
	MemoryStorage *string `pulumi:"memoryStorage"`
	// A meaningful name to identify the subscription
	Name *string `pulumi:"name"`
	// Payment method for the requested subscription. If credit card is specified, the payment method Id must be defined.
	PaymentMethod *string `pulumi:"paymentMethod"`
	// A valid payment method pre-defined in the current account
	PaymentMethodId *string `pulumi:"paymentMethodId"`
}

// The set of arguments for constructing a Subscription resource.
type SubscriptionArgs struct {
	// An allowlist object
	Allowlist SubscriptionAllowlistPtrInput
	// A cloud provider object
	CloudProvider SubscriptionCloudProviderInput
	// Information about the planned databases used to optimise the database infrastructure. This information is only used when
	// creating a new subscription and any changes will be ignored after this.
	CreationPlan SubscriptionCreationPlanPtrInput
	// Memory storage preference: either ‘ram’ or a combination of 'ram-and-flash’
	MemoryStorage pulumi.StringPtrInput
	// A meaningful name to identify the subscription
	Name pulumi.StringPtrInput
	// Payment method for the requested subscription. If credit card is specified, the payment method Id must be defined.
	PaymentMethod pulumi.StringPtrInput
	// A valid payment method pre-defined in the current account
	PaymentMethodId pulumi.StringPtrInput
}

func (SubscriptionArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*subscriptionArgs)(nil)).Elem()
}

type SubscriptionInput interface {
	pulumi.Input

	ToSubscriptionOutput() SubscriptionOutput
	ToSubscriptionOutputWithContext(ctx context.Context) SubscriptionOutput
}

func (*Subscription) ElementType() reflect.Type {
	return reflect.TypeOf((**Subscription)(nil)).Elem()
}

func (i *Subscription) ToSubscriptionOutput() SubscriptionOutput {
	return i.ToSubscriptionOutputWithContext(context.Background())
}

func (i *Subscription) ToSubscriptionOutputWithContext(ctx context.Context) SubscriptionOutput {
	return pulumi.ToOutputWithContext(ctx, i).(SubscriptionOutput)
}

// SubscriptionArrayInput is an input type that accepts SubscriptionArray and SubscriptionArrayOutput values.
// You can construct a concrete instance of `SubscriptionArrayInput` via:
//
//	SubscriptionArray{ SubscriptionArgs{...} }
type SubscriptionArrayInput interface {
	pulumi.Input

	ToSubscriptionArrayOutput() SubscriptionArrayOutput
	ToSubscriptionArrayOutputWithContext(context.Context) SubscriptionArrayOutput
}

type SubscriptionArray []SubscriptionInput

func (SubscriptionArray) ElementType() reflect.Type {
	return reflect.TypeOf((*[]*Subscription)(nil)).Elem()
}

func (i SubscriptionArray) ToSubscriptionArrayOutput() SubscriptionArrayOutput {
	return i.ToSubscriptionArrayOutputWithContext(context.Background())
}

func (i SubscriptionArray) ToSubscriptionArrayOutputWithContext(ctx context.Context) SubscriptionArrayOutput {
	return pulumi.ToOutputWithContext(ctx, i).(SubscriptionArrayOutput)
}

// SubscriptionMapInput is an input type that accepts SubscriptionMap and SubscriptionMapOutput values.
// You can construct a concrete instance of `SubscriptionMapInput` via:
//
//	SubscriptionMap{ "key": SubscriptionArgs{...} }
type SubscriptionMapInput interface {
	pulumi.Input

	ToSubscriptionMapOutput() SubscriptionMapOutput
	ToSubscriptionMapOutputWithContext(context.Context) SubscriptionMapOutput
}

type SubscriptionMap map[string]SubscriptionInput

func (SubscriptionMap) ElementType() reflect.Type {
	return reflect.TypeOf((*map[string]*Subscription)(nil)).Elem()
}

func (i SubscriptionMap) ToSubscriptionMapOutput() SubscriptionMapOutput {
	return i.ToSubscriptionMapOutputWithContext(context.Background())
}

func (i SubscriptionMap) ToSubscriptionMapOutputWithContext(ctx context.Context) SubscriptionMapOutput {
	return pulumi.ToOutputWithContext(ctx, i).(SubscriptionMapOutput)
}

type SubscriptionOutput struct{ *pulumi.OutputState }

func (SubscriptionOutput) ElementType() reflect.Type {
	return reflect.TypeOf((**Subscription)(nil)).Elem()
}

func (o SubscriptionOutput) ToSubscriptionOutput() SubscriptionOutput {
	return o
}

func (o SubscriptionOutput) ToSubscriptionOutputWithContext(ctx context.Context) SubscriptionOutput {
	return o
}

// An allowlist object
func (o SubscriptionOutput) Allowlist() SubscriptionAllowlistPtrOutput {
	return o.ApplyT(func(v *Subscription) SubscriptionAllowlistPtrOutput { return v.Allowlist }).(SubscriptionAllowlistPtrOutput)
}

// A cloud provider object
func (o SubscriptionOutput) CloudProvider() SubscriptionCloudProviderOutput {
	return o.ApplyT(func(v *Subscription) SubscriptionCloudProviderOutput { return v.CloudProvider }).(SubscriptionCloudProviderOutput)
}

// Information about the planned databases used to optimise the database infrastructure. This information is only used when
// creating a new subscription and any changes will be ignored after this.
func (o SubscriptionOutput) CreationPlan() SubscriptionCreationPlanPtrOutput {
	return o.ApplyT(func(v *Subscription) SubscriptionCreationPlanPtrOutput { return v.CreationPlan }).(SubscriptionCreationPlanPtrOutput)
}

// Memory storage preference: either ‘ram’ or a combination of 'ram-and-flash’
func (o SubscriptionOutput) MemoryStorage() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *Subscription) pulumi.StringPtrOutput { return v.MemoryStorage }).(pulumi.StringPtrOutput)
}

// A meaningful name to identify the subscription
func (o SubscriptionOutput) Name() pulumi.StringOutput {
	return o.ApplyT(func(v *Subscription) pulumi.StringOutput { return v.Name }).(pulumi.StringOutput)
}

// Payment method for the requested subscription. If credit card is specified, the payment method Id must be defined.
func (o SubscriptionOutput) PaymentMethod() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *Subscription) pulumi.StringPtrOutput { return v.PaymentMethod }).(pulumi.StringPtrOutput)
}

// A valid payment method pre-defined in the current account
func (o SubscriptionOutput) PaymentMethodId() pulumi.StringOutput {
	return o.ApplyT(func(v *Subscription) pulumi.StringOutput { return v.PaymentMethodId }).(pulumi.StringOutput)
}

type SubscriptionArrayOutput struct{ *pulumi.OutputState }

func (SubscriptionArrayOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*[]*Subscription)(nil)).Elem()
}

func (o SubscriptionArrayOutput) ToSubscriptionArrayOutput() SubscriptionArrayOutput {
	return o
}

func (o SubscriptionArrayOutput) ToSubscriptionArrayOutputWithContext(ctx context.Context) SubscriptionArrayOutput {
	return o
}

func (o SubscriptionArrayOutput) Index(i pulumi.IntInput) SubscriptionOutput {
	return pulumi.All(o, i).ApplyT(func(vs []interface{}) *Subscription {
		return vs[0].([]*Subscription)[vs[1].(int)]
	}).(SubscriptionOutput)
}

type SubscriptionMapOutput struct{ *pulumi.OutputState }

func (SubscriptionMapOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*map[string]*Subscription)(nil)).Elem()
}

func (o SubscriptionMapOutput) ToSubscriptionMapOutput() SubscriptionMapOutput {
	return o
}

func (o SubscriptionMapOutput) ToSubscriptionMapOutputWithContext(ctx context.Context) SubscriptionMapOutput {
	return o
}

func (o SubscriptionMapOutput) MapIndex(k pulumi.StringInput) SubscriptionOutput {
	return pulumi.All(o, k).ApplyT(func(vs []interface{}) *Subscription {
		return vs[0].(map[string]*Subscription)[vs[1].(string)]
	}).(SubscriptionOutput)
}

func init() {
	pulumi.RegisterInputType(reflect.TypeOf((*SubscriptionInput)(nil)).Elem(), &Subscription{})
	pulumi.RegisterInputType(reflect.TypeOf((*SubscriptionArrayInput)(nil)).Elem(), SubscriptionArray{})
	pulumi.RegisterInputType(reflect.TypeOf((*SubscriptionMapInput)(nil)).Elem(), SubscriptionMap{})
	pulumi.RegisterOutputType(SubscriptionOutput{})
	pulumi.RegisterOutputType(SubscriptionArrayOutput{})
	pulumi.RegisterOutputType(SubscriptionMapOutput{})
}
